### ISSUE TITLE
Update the energy calculations based on the new distribution of the GW values

### ISSUE THREAD

**Issue by JZF07** [KTH-dESA/FAO#119]
Update the energy calculations based on the new distribution of the GW values on the cropland area. 
Currently the energy calculation is being done based on WEAP results and then distributed over the cropland layer which is resulting in high impact of GW table depth on energy demand and PV sizing. This approach should be updated to distribute the WEAP outputs and GW depth then carrying on the energy calculation and butane phase out scenarios.

**Comment by camiloramirezgo** [comment]
This issue depends on issue #118

**Comment by camiloramirezgo** [comment]
Not required anymore
