### ISSUE TITLE
Fix PV installation graph

### ISSUE THREAD

**Issue by JZF07** [KTH-dESA/FAO#121]
The PV graph does not show consistence increase in (previous PV capacity) if compared to (new PV capacity).

**Comment by JZF07** [comment]
Suggested solution: 

souss_massa1.loc[souss_massa1['Year']==2020, 'PV_new_cap(MW)'] = 0
souss_massa1.loc[souss_massa1['Year']==2020, 'PV_installed_cap(MW)'] = souss_massa1['cap_max(MW)']
        
souss_massa1.loc[souss_massa1['Year']!=2020, 'PV_installed_cap(MW)'] = (souss_massa1['cap_max(MW)'].shift(1) + souss_massa1['PV_new_cap(MW)'])

souss_massa1.loc[souss_massa1['Year']!=2020, 'PV_new_cap(MW)'] = (souss_massa1['cap_max(MW)'] - souss_massa1['PV_installed_cap(MW)'].shift(1))

             
souss_massa1.loc[(souss_massa1['Year']!=2020) & (souss_massa1['PV_new_cap(MW)'] == 0), 'PV_installed_cap(MW)'] = souss_massa1['PV_installed_cap(MW)'].shift(1)

**Comment by camiloramirezgo** [comment]
I did some research and I got to a solution using a method from pandas `cummax()`, which calculates the cumulative max value of a series. So it goes through the values of a series and checks the previous and the current value and assings whichever is greatest. Then, I had to loop through each `Demand point` group and calculate the `cummax()` for the `cap_max(MW)` variable. Afterwards, I calculate the new capacity by just getting the difference with the previous and current values using the `shift(1)` function: 
```python
pv_istalled_cap = pd.Series(dtype=float) #inicialize a pandas series that will be populated with the cumulative max of the max capacity of each point group
for index, group in souss_massa1.groupby('Demad point'): # loops through each demand point set of data
    pv_istalled_cap = pv_istalled_cap.append(group['cap_max(MW)'].cummax()) # calculates the cummmax() for the demand point and append the values to the pv_installed_capacity
souss_massa1['PV_installed_cap(MW)'] = pv_istalled_cap
souss_massa1['PV_new_cap(MW)'] = souss_massa1['PV_installed_cap(MW)'] - souss_massa1['PV_installed_cap(MW)'].shift(1)
souss_massa1.loc[souss_massa1['Year']==2020, 'PV_new_cap(MW)'] = 0
```
I did some tests with dummy data and got good results:
![image](https://user-images.githubusercontent.com/12953752/108064996-b2dc8d00-705d-11eb-8c8a-a0ae6a495c81.png)
