### ISSUE TITLE
LCOE - change the characteristic of wind turbine

### ISSUE THREAD

**Issue by JZF07** [KTH-dESA/FAO#14]
Update the technical and economic characteristics of the wind turbine technology used in the LCOE code. The current wind technology seems to be more relevant for min-grid but not very representative for small scale irrigation. 

This might require updating the following parameters: 

- Wind Turbine height
- Speed 
- Capital cost
- O&M cost
- Learning rate
- Capacity factor.
- Others

**Comment by JZF07** [comment]
Cherif et al, 2011 developed a model using PV and small scale wind turbine to power RO desalination unit in South of Tunisia. A a 10 kW rated power wind turbine was chosen for this study. The wind turbine type is a direct drive based on a synchronous generator. It is characterized by a starting speed of 3.4 m/s and a rated speed of 13 m/s [12]. The wind turbine has the following characteristics:
* Rotor diameter e D = 7 m
* Hub height e zhub = 18.3 m
* Power coefficient e Cp_max = 0.25
* Generator efficiency e h = 80%
source: https://www.sciencedirect.com/science/article/pii/S0360544211005408

**Comment by camiloramirezgo** [comment]
Done.
