### ISSUE TITLE
LCOE - Apply learning rate for renewable technologies 

### ISSUE THREAD

**Issue by JZF07** [KTH-dESA/FAO#15]
Renewable energy technologies have high capital cost (in most cases), however this cost is expected to drop due to the learning rate which is defined as the drop in technology cost due to doubling the capacity or 'learning by doing'. 

The code should account for solar and wind learning rates and project that for the coming years. 

Sources such as WEO 2018 and IRENA can be used to obtain such data.

**Comment by camiloramirezgo** [comment]
Done.
